# fly.toml app configuration file generated for moviegouz on 2025-01-14T10:49:47+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'moviegouz'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
